# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DNS-ZoneParse
version:      0.95
version_from: lib/DNS/ZoneParse.pm
installdirs:  site
requires:
    Storable:                      0.407
    Test::More:                    0.31

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
